config/routes.rb
Rails.application.routes.draw do
  get '/game', to: 'longest_word#game'

  get '/score', to: 'longest_word#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/longest_word_controller.rb
class LongestWordController < ApplicationController

  def game
    @grid = generate_grid(9)
     @start_time = Time.now
  end

  def score
    @end_time = Time.now
    @start_time = Time.parse(params[:start_time])
    @total_time = @end_time - @start_time
    @word = params[:word]
    @compute_score = compute_score(@word, @total_time)
    @score_and_message = score_and_message(@word, @grid, @total_time)
  end


  def generate_grid(grid_size)
  Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end



def compute_score(attempt, time_taken)
  ((time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)).round
end

def score_and_message(attempt, grid, time)
 if @compute_score > 0
  return "Well done"
else
  return "you suck"
end
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/longest_word_helper.rb
module LongestWordHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longest_word/game.html.erb
<h1>LongestWord#game</h1>
<p>Your grid is:  <%= @grid %> </p>



<form action="/score">
  <label for="question">Type your word</label>
  <input type="hidden" id="start_time" name="start_time" value= "<%= @start_time %>">
  <input type="text" id="longestword" name="word" placeholder="Type a word">
  <input type="submit" value="Go on!">
</form>

app/views/longest_word/score.html.erb
<h1>LongestWord#score</h1>
<p>Find me in app/views/longest_word/score.html.erb</p>

<%= "Word:" %> <%= @word %> <br>
<%= "Score:" %> <%= @compute_score %> <br>
<%= "Time:" %> <%= @total_time %> <br>
<%= @score_and_message %> <br>


<%= link_to("game", game_path)  %>